version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ashish
      POSTGRES_PASSWORD: 07122000
      POSTGRES_DB: distributed_filestore_db
      ports:
        -"5432:5432"
      volumes:
        -postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: distributed_filestore_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
  redis_data: